level_0:
  global_frame: level_9_map
  maps_package: multimap_server
  maps:
    localization: maps/L9/mbc_L9.yaml
    routes: maps/L9/routes.yaml
level_1:
  global_frame: level_10_map
  maps_package: multimap_server
  maps:
    localization: maps/L10/mbc_L10.yaml
    routes: maps/L10/routes.yaml
